default: &default
  adapter: sqlite3
  pool: 5
  host: localhost
  username: pguser
  password: 
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: universcours_production
  pool: 5
  username: pguser
  password: 
